[project]
name = "ccwc"
version = "0.1.0"
description = "Unix like command line tool wc"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.9.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
